name: Internal PyPI Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: ""

      - name: Create a GitHub release
        if: steps.tag_version.outcome == 'success'
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}

  build:
    uses: adjust/githubWorkflows/.github/workflows/automateBuildPushWheel.yml@v8.1.15
    needs: [release]
    with:
      python_version: 3.12
