on: [push, pull_request]
name: "SQLAlchemy 2.0 supported versions"
jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        clickhouse-version:
          - 23.8.4.69
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:${{ matrix.clickhouse-version }}
        ports:
          - 8123:8123
          - 9000:9000

    name: ${{ matrix.python-version }} SA=max-supported
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test requirements
        run: |
          pip install --upgrade pip setuptools wheel
          python testsrequire.py
          python setup.py develop
          # Limit each test time execution.
          pip install pytest-timeout
      - name: Install SQLAlchemy
        run: pip install --upgrade "sqlalchemy>=2.0.0,<2.0.44"
      - name: Run tests
        run: pytest --maxfail=1 --timeout=10 -v
        timeout-minutes: 2
